import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import AuthProvider, { useAuth } from "@/context/AuthContext";
import { CompanyProvider } from "@/context/CompanyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CompanyProvider>
            {children}
            <ToastContainer />
          </CompanyProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
